---
abstract: 'google.com/voice services'
author:
  - 'Glen Hinkle <tempire@cpan.org>'
build_requires:
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Google-Voice
requires:
  IO::Socket::SSL: 0
  Mojo::Base: 0
  Mojo::ByteStream: 0
  Mojo::Client: 0
  Mojo::JSON: 0
  constant: 0
version: 0.01
